use travis releases instead (#6)
* use travis releases instead

* move version check to build

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -5,6 +5,15 @@ DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 VERSION=$(cat $DIR/../version)
 
 # Build Script
+versionCheck() {
+    if git rev-parse ${VERSION} >/dev/null 2>&1; then
+        echo "Found tag"
+        exit 1
+    else
+        echo "Tag not found"
+    fi
+}
+
 buildContainer() {
     cd $DIR/..
     docker build -t nona-s3-pull .
@@ -27,6 +36,7 @@ testContainer() {
     done
 }
 
+versionCheck
 buildContainer
 testContainer
 
